name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: cd backend && npm ci
      
  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: cd backend && npm test
      
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
          
  buildpush-docker:
    needs: [build-backend, test-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsvideodemo:${{ github.run_number }}
  deploy:
    needs: buildpush-docker
    runs-on: ubuntu-latest
    steps:
      -
          name: Login to Azure
          uses: azure/webapps-deploy@v2
          with:
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            app-name: devopsvideodemo-app
            images: ${{ secrets.DOCKERHUB_USERNAME }}/devopsvideodemo:${{ github.run_number }}
